{
 "title": "Flask app",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_http_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  rate(app_http_requests_total{status=~\"5..\"}[5m])\r\n  /\r\n  clamp_min(rate(app_http_requests_total[5m]), 1)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Writes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "rate(app_db_writes_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_request_latency_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flask app – request rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(app_http_requests_total{method=\"GET\"}[1m])",
     "legendFormat": "{{app_http_requests_total}} {{method}} {{endpoint}}"
    }
   ]
  }
 ]
}