{
 "title": "PostgreSQL metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_database_size_bytes", "legendFormat": "{{datname}}" }
   ]
  },
  {
   "title": "Database connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "pg_stat_database_numbackends", "legendFormat": "{{datname}}" }
   ]
  },
  {
   "title": "Acive vs Idle connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (datname, state) (\r\n  pg_stat_activity_count{state=~\"active|idle\"}\r\n)",
     "legendFormat": "{{state}} {{datname}}"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(\r\n  rate(pg_stat_database_blks_hit[5m])\r\n)\r\n/\r\n(\r\n  rate(pg_stat_database_blks_hit[5m])\r\n  +\r\n  rate(pg_stat_database_blks_read[5m])\r\n)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (datname, instance) (\r\n  rate(pg_stat_database_xact_commit[5m])\r\n  +\r\n  rate(pg_stat_database_xact_rollback[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}